services:
  frontend:
    container_name: quizwizz-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_PROXY_TARGET=http://backend:8080
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - quizwizz-network
    depends_on:
      - backend

  backend:
    container_name: quizwizz-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/backend:/app
    networks:
      - quizwizz-network

networks:
  quizwizz-network:
    driver: bridge

volumes:
  frontend_node_modules: